/**********************************************************************
            --- KDevelop (KDlgEdit)  generated file ---                

            Last generated: Thu Mar 30 21:34:14 2000

            DO NOT EDIT!!!  This file will be automatically
            regenerated by KDevelop.  All changes will be lost.

**********************************************************************/
#include <kapp.h>
#include <klocale.h>
#include "corewidgetdlg.h"

void  CoreWidgetDlg::initDialog(){
  this->resize(400,240);
  this->setMinimumSize(0,0);
  QLabel_1= new QLabel(this,"NoName");
  QLabel_1->setGeometry(10,10,120,30);
  QLabel_1->setMinimumSize(0,0);
  QLabel_1->setText(i18n("Id"));

  QLabel_2= new QLabel(this,"NoName");
  QLabel_2->setGeometry(10,40,120,30);
  QLabel_2->setMinimumSize(0,0);
  QLabel_2->setText(i18n("Class"));

  QLabel_3= new QLabel(this,"NoName");
  QLabel_3->setGeometry(10,70,120,30);
  QLabel_3->setMinimumSize(0,0);
  QLabel_3->setText(i18n("Style"));

  QLabel_4= new QLabel(this,"NoName");
  QLabel_4->setGeometry(10,100,120,30);
  QLabel_4->setMinimumSize(0,0);
  QLabel_4->setText(i18n("Title"));

  lineId= new QLineEdit(this,"NoName");
  lineId->setGeometry(130,10,260,25);
  lineId->setMinimumSize(0,0);

  lineClass= new QLineEdit(this,"NoName");
  lineClass->setGeometry(130,40,260,25);
  lineClass->setMinimumSize(0,0);

  lineStyle= new QLineEdit(this,"NoName");
  lineStyle->setGeometry(130,70,260,25);
  lineStyle->setMinimumSize(0,0);

  lineTitle= new QLineEdit(this,"NoName");
  lineTitle->setGeometry(130,100,260,25);
  lineTitle->setMinimumSize(0,0);

  KSeparator_1= new KSeparator(this,"NoName");
  KSeparator_1->setGeometry(10,130,380,10);
  KSeparator_1->setMinimumSize(0,0);
  KSeparator_1->setOrientation(KSeparator::HLine);

  QLabel_5= new QLabel(this,"NoName");
  QLabel_5->setGeometry(10,140,380,30);
  QLabel_5->setMinimumSize(0,0);
  QLabel_5->setText(i18n("Internationalization Attributes"));

  QLabel_6= new QLabel(this,"NoName");
  QLabel_6->setGeometry(10,170,120,30);
  QLabel_6->setMinimumSize(0,0);
  QLabel_6->setText(i18n("Lang"));

  QLabel_7= new QLabel(this,"NoName");
  QLabel_7->setGeometry(10,200,120,30);
  QLabel_7->setMinimumSize(0,0);
  QLabel_7->setText(i18n("Dir"));

  lineLang= new QLineEdit(this,"NoName");
  lineLang->setGeometry(130,170,260,25);
  lineLang->setMinimumSize(0,0);

  lineDir= new QLineEdit(this,"NoName");
  lineDir->setGeometry(130,200,260,25);
  lineDir->setMinimumSize(0,0);

}
