/**********************************************************************
            --- KDevelop (KDlgEdit)  generated file ---                

            Last generated: Thu Mar 30 18:34:19 2000

            DO NOT EDIT!!!  This file will be automatically
            regenerated by KDevelop.  All changes will be lost.

**********************************************************************/
#include <kapp.h>
#include <klocale.h>
#include "eventswidgetdlg.h"

void  EventsWidgetDlg::initDialog(){
  this->resize(400,320);
  this->setMinimumSize(0,0);
  QLabel_1= new QLabel(this,"NoName");
  QLabel_1->setGeometry(10,10,120,30);
  QLabel_1->setMinimumSize(0,0);
  QLabel_1->setText(i18n("OnClick"));

  lineClick= new QLineEdit(this,"NoName");
  lineClick->setGeometry(130,10,260,25);
  lineClick->setMinimumSize(0,0);

  QLabel_2= new QLabel(this,"NoName");
  QLabel_2->setGeometry(10,40,120,30);
  QLabel_2->setMinimumSize(0,0);
  QLabel_2->setText(i18n("OnDblClick"));

  QLabel_3= new QLabel(this,"NoName");
  QLabel_3->setGeometry(10,70,120,30);
  QLabel_3->setMinimumSize(0,0);
  QLabel_3->setText(i18n("OnMouseDown"));

  lineDblClick= new QLineEdit(this,"NoName");
  lineDblClick->setGeometry(130,40,260,25);
  lineDblClick->setMinimumSize(0,0);

  lineMouseDown= new QLineEdit(this,"NoName");
  lineMouseDown->setGeometry(130,70,260,25);
  lineMouseDown->setMinimumSize(0,0);

  QLabel_4= new QLabel(this,"NoName");
  QLabel_4->setGeometry(10,100,120,30);
  QLabel_4->setMinimumSize(0,0);
  QLabel_4->setText(i18n("OnMouseUp"));

  lineMouseUp= new QLineEdit(this,"NoName");
  lineMouseUp->setGeometry(130,100,260,25);
  lineMouseUp->setMinimumSize(0,0);

  QLabel_5= new QLabel(this,"NoName");
  QLabel_5->setGeometry(10,130,120,30);
  QLabel_5->setMinimumSize(0,0);
  QLabel_5->setText(i18n("OnMouseOver"));

  lineMouseOver= new QLineEdit(this,"NoName");
  lineMouseOver->setGeometry(130,130,260,25);
  lineMouseOver->setMinimumSize(0,0);

  QLabel_6= new QLabel(this,"NoName");
  QLabel_6->setGeometry(10,160,120,30);
  QLabel_6->setMinimumSize(0,0);
  QLabel_6->setText(i18n("OnMouseMove"));

  lineMouseMove= new QLineEdit(this,"NoName");
  lineMouseMove->setGeometry(130,160,260,25);
  lineMouseMove->setMinimumSize(0,0);

  QLabel_7= new QLabel(this,"NoName");
  QLabel_7->setGeometry(10,190,120,30);
  QLabel_7->setMinimumSize(0,0);
  QLabel_7->setText(i18n("OnMouseOut"));

  lineMouseOut= new QLineEdit(this,"NoName");
  lineMouseOut->setGeometry(130,190,260,25);
  lineMouseOut->setMinimumSize(0,0);

  QLabel_8= new QLabel(this,"NoName");
  QLabel_8->setGeometry(10,220,120,30);
  QLabel_8->setMinimumSize(0,0);
  QLabel_8->setText(i18n("OnKeyPress"));

  lineKeyPress= new QLineEdit(this,"NoName");
  lineKeyPress->setGeometry(130,220,260,25);
  lineKeyPress->setMinimumSize(0,0);

  QLabel_9= new QLabel(this,"NoName");
  QLabel_9->setGeometry(10,250,120,30);
  QLabel_9->setMinimumSize(0,0);
  QLabel_9->setText(i18n("OnKeyDown"));

  lineKeyDown= new QLineEdit(this,"NoName");
  lineKeyDown->setGeometry(130,250,260,25);
  lineKeyDown->setMinimumSize(0,0);

  QLabel_10= new QLabel(this,"NoName");
  QLabel_10->setGeometry(10,280,120,30);
  QLabel_10->setMinimumSize(0,0);
  QLabel_10->setText(i18n("OnKeyUp"));

  lineKeyUp= new QLineEdit(this,"NoName");
  lineKeyUp->setGeometry(130,280,260,25);
  lineKeyUp->setMinimumSize(0,0);

}
