/**********************************************************************
            --- KDevelop (KDlgEdit)  generated file ---                

            Last generated: Tue Nov 30 22:51:22 1999

            DO NOT EDIT!!!  This file will be automatically
            regenerated by KDevelop.  All changes will be lost.

**********************************************************************/
#include <kapp.h>
#include <klocale.h>
#include "tagadlg.h"

void  TagADlg::initDialog(){
  this->setGeometry(200,200,400,180);
  this->setMinimumSize(0,0);
  QLabel_1= new QLabel(this,"NoName");
  QLabel_1->setGeometry(10,10,100,30);
  QLabel_1->setMinimumSize(0,0);
  QLabel_1->setText(i18n("HREF"));

  comboHREF= new QComboBox(true,this,"NoName");
  comboHREF->setGeometry(110,10,240,25);
  comboHREF->setMinimumSize(0,0);

  buttonHREF= new QPushButton(this,"NoName");
  buttonHREF->setGeometry(355,10,35,25);
  buttonHREF->setMinimumSize(0,0);
  buttonHREF->setText(i18n("..."));

  QLabel_2= new QLabel(this,"NoName");
  QLabel_2->setGeometry(10,40,100,30);
  QLabel_2->setMinimumSize(0,0);
  QLabel_2->setText(i18n("Target"));

  comboTarget= new QComboBox(true,this,"NoName");
  comboTarget->setGeometry(110,40,280,25);
  comboTarget->setMinimumSize(0,0);

  QLabel_3= new QLabel(this,"NoName");
  QLabel_3->setGeometry(10,70,100,30);
  QLabel_3->setMinimumSize(0,0);
  QLabel_3->setText(i18n("Name"));

  lineName= new QLineEdit(this,"NoName");
  lineName->setGeometry(110,70,280,25);
  lineName->setMinimumSize(0,0);

  QLabel_4= new QLabel(this,"NoName");
  QLabel_4->setGeometry(10,100,100,30);
  QLabel_4->setMinimumSize(0,0);
  QLabel_4->setText(i18n("Description"));

  lineDescription= new QLineEdit(this,"NoName");
  lineDescription->setGeometry(110,100,280,25);
  lineDescription->setMinimumSize(0,0);
}
