/**********************************************************************
            --- KDevelop (KDlgEdit)  generated file ---                

            Last generated: Mon Apr 3 18:20:33 2000

            DO NOT EDIT!!!  This file will be automatically
            regenerated by KDevelop.  All changes will be lost.

**********************************************************************/
#include <kapp.h>
#include <qtooltip.h>
#include "tagbody.h"
#include <klocale.h>

void  TagBody::initDialog(){
  this->resize(400,320);
  this->setMinimumSize(0,0);
  labelBGImage= new QLabel(this,"labelBGImage");
  labelBGImage->setGeometry(10,10,110,30);
  labelBGImage->setMinimumSize(0,0);
  labelBGImage->setText(i18n("BG Image"));

  labelBGColor= new QLabel(this,"labelBGColor");
  labelBGColor->setGeometry(10,40,160,30);
  labelBGColor->setMinimumSize(0,0);
  labelBGColor->setText(i18n("BG Color"));

  labelTextColor= new QLabel(this,"labelTextColor");
  labelTextColor->setGeometry(10,70,160,30);
  labelTextColor->setMinimumSize(0,0);
  labelTextColor->setText(i18n("Text Color"));

  labelActiveLinkColor= new QLabel(this,"labelActiveLinkColor");
  labelActiveLinkColor->setGeometry(10,130,160,30);
  labelActiveLinkColor->setMinimumSize(0,0);
  labelActiveLinkColor->setText(i18n("Active Link Color"));

  lineBGImage= new QLineEdit(this,"NoName");
  lineBGImage->setGeometry(120,10,220,25);
  lineBGImage->setMinimumSize(0,0);

  buttonFileSelect= new QPushButton(this,"NoName");
  buttonFileSelect->setGeometry(350,10,40,25);
  buttonFileSelect->setMinimumSize(0,0);
  QToolTip::add(buttonFileSelect,i18n("Select background image"));
  buttonFileSelect->setText(i18n("..."));

  comboBGColor= new QComboBox(true,this,"NoName");
  comboBGColor->setGeometry(170,40,170,25);
  comboBGColor->setMinimumSize(0,0);

  cButtonBGColor= new KColorButton(this,"NoName");
  cButtonBGColor->setGeometry(350,40,40,25);
  cButtonBGColor->setMinimumSize(0,0);
  cButtonBGColor->setText(i18n("Button"));

  comboTextColor= new QComboBox(true,this,"NoName");
  comboTextColor->setGeometry(170,70,170,25);
  comboTextColor->setMinimumSize(0,0);

  cButtonTextColor= new KColorButton(this,"NoName");
  cButtonTextColor->setGeometry(350,70,40,25);
  cButtonTextColor->setMinimumSize(0,0);
  cButtonTextColor->setText(i18n("Button"));

  comboLinkColor= new QComboBox(true,this,"NoName");
  comboLinkColor->setGeometry(170,100,170,25);
  comboLinkColor->setMinimumSize(0,0);

  cButtonLinkColor= new KColorButton(this,"NoName");
  cButtonLinkColor->setGeometry(350,100,40,25);
  cButtonLinkColor->setMinimumSize(0,0);
  cButtonLinkColor->setText(i18n("Button"));

  comboALinkColor= new QComboBox(true,this,"NoName");
  comboALinkColor->setGeometry(170,130,170,25);
  comboALinkColor->setMinimumSize(0,0);

  cButtonALinkColor= new KColorButton(this,"NoName");
  cButtonALinkColor->setGeometry(350,130,40,25);
  cButtonALinkColor->setMinimumSize(0,0);
  cButtonALinkColor->setText(i18n("Button"));

  QLabel_8= new QLabel(this,"NoName");
  QLabel_8->setGeometry(10,160,160,30);
  QLabel_8->setMinimumSize(0,0);
  QLabel_8->setText(i18n("Visited Link Color"));

  comboVLinkColor= new QComboBox(true,this,"NoName");
  comboVLinkColor->setGeometry(170,160,170,25);
  comboVLinkColor->setMinimumSize(0,0);

  cButtonVLinkColor= new KColorButton(this,"NoName");
  cButtonVLinkColor->setGeometry(350,160,40,25);
  cButtonVLinkColor->setMinimumSize(0,0);
  cButtonVLinkColor->setText(i18n("Button"));

  QLabel_7= new QLabel(this,"NoName");
  QLabel_7->setGeometry(10,100,160,30);
  QLabel_7->setMinimumSize(0,0);
  QLabel_7->setText(i18n("Link Color"));

  KSeparator_1= new KSeparator(this,"NoName");
  KSeparator_1->setGeometry(10,190,380,20);
  KSeparator_1->setMinimumSize(0,0);
  KSeparator_1->setOrientation(KSeparator::HLine);

  QLabel_7= new QLabel(this,"NoName");
  QLabel_7->setGeometry(10,220,100,30);
  QLabel_7->setMinimumSize(0,0);
  QLabel_7->setText(i18n("On Load :"));

  lineOnLoad= new QLineEdit(this,"NoName");
  lineOnLoad->setGeometry(110,220,280,25);
  lineOnLoad->setMinimumSize(0,0);

  QLabel_8= new QLabel(this,"NoName");
  QLabel_8->setGeometry(10,250,100,30);
  QLabel_8->setMinimumSize(0,0);
  QLabel_8->setText(i18n("On Unload :"));

  lineOnUnload= new QLineEdit(this,"NoName");
  lineOnUnload->setGeometry(110,250,280,25);
  lineOnUnload->setMinimumSize(0,0);

}
