/**********************************************************************
            --- KDevelop (KDlgEdit)  generated file ---                

            Last generated: Sun Apr 2 02:58:50 2000

            DO NOT EDIT!!!  This file will be automatically
            regenerated by KDevelop.  All changes will be lost.

**********************************************************************/
#include <kapp.h>
#include <klocale.h>
#include "tagformtextareadlg.h"

void  TagFormTextareaDlg::initDialog(){
  this->resize(400,110);
  this->setMinimumSize(0,0);
  QLabel_1= new QLabel(this,"NoName");
  QLabel_1->setGeometry(10,10,120,30);
  QLabel_1->setMinimumSize(0,0);
  QLabel_1->setText(i18n("Name"));

  QLabel_2= new QLabel(this,"NoName");
  QLabel_2->setGeometry(10,40,120,30);
  QLabel_2->setMinimumSize(0,0);
  QLabel_2->setText(i18n("Rows"));

  QLabel_3= new QLabel(this,"NoName");
  QLabel_3->setGeometry(10,70,120,30);
  QLabel_3->setMinimumSize(0,0);
  QLabel_3->setText(i18n("Cols"));

  lineName= new QLineEdit(this,"NoName");
  lineName->setGeometry(130,10,260,25);
  lineName->setMinimumSize(0,0);

  lineRows= new QLineEdit(this,"NoName");
  lineRows->setGeometry(130,40,260,25);
  lineRows->setMinimumSize(0,0);

  lineCols= new QLineEdit(this,"NoName");
  lineCols->setGeometry(130,70,260,25);
  lineCols->setMinimumSize(0,0);

}
