/**********************************************************************
            --- KDevelop (KDlgEdit)  generated file ---                

            Last generated: Sun Apr 2 02:50:08 2000

            DO NOT EDIT!!!  This file will be automatically
            regenerated by KDevelop.  All changes will be lost.

**********************************************************************/
#include <kapp.h>
#include <klocale.h>
#include "tagformtext.h"

void  TagFormText::initDialog(){
  this->resize(400,140);
  this->setMinimumSize(0,0);
  lineMaxLen= new QLineEdit(this,"NoName");
  lineMaxLen->setGeometry(130,100,80,25);
  lineMaxLen->setMinimumSize(0,0);

  lineSize= new QLineEdit(this,"NoName");
  lineSize->setGeometry(310,100,80,25);
  lineSize->setMinimumSize(0,0);

  QLabel_1= new QLabel(this,"NoName");
  QLabel_1->setGeometry(10,10,120,30);
  QLabel_1->setMinimumSize(0,0);
  QLabel_1->setText(i18n("Name:"));

  lineName= new QLineEdit(this,"NoName");
  lineName->setGeometry(130,10,260,25);
  lineName->setMinimumSize(0,0);

  QLabel_2= new QLabel(this,"NoName");
  QLabel_2->setGeometry(10,40,120,30);
  QLabel_2->setMinimumSize(0,0);
  QLabel_2->setText(i18n("Value:"));

  lineValue= new QLineEdit(this,"NoName");
  lineValue->setGeometry(130,40,260,25);
  lineValue->setMinimumSize(0,0);

  QLabel_3= new QLabel(this,"NoName");
  QLabel_3->setGeometry(230,100,80,30);
  QLabel_3->setMinimumSize(0,0);
  QLabel_3->setText(i18n("Size:"));

  QLabel_4= new QLabel(this,"NoName");
  QLabel_4->setGeometry(10,100,120,30);
  QLabel_4->setMinimumSize(0,0);
  QLabel_4->setText(i18n("MaxLength:"));

}
