/**********************************************************************
            --- KDevelop (KDlgEdit)  generated file ---                

            Last generated: Sun Apr 2 14:17:22 2000

            DO NOT EDIT!!!  This file will be automatically
            regenerated by KDevelop.  All changes will be lost.

**********************************************************************/
#include <kapp.h>
#include <klocale.h>
#include "tagforminput.h"

void  TagFormInput::initDialog(){
  this->resize(400,320);
  this->setMinimumSize(0,0);
  QLabel_1= new QLabel(this,"NoName");
  QLabel_1->setGeometry(10,10,90,30);
  QLabel_1->setMinimumSize(0,0);
  QLabel_1->setText(i18n("Type:"));

  comboType= new QComboBox(this,"NoName");
  comboType->setGeometry(100,10,120,25);
  comboType->setMinimumSize(0,0);
  comboType->insertItem("text");
  comboType->insertItem("password");
  comboType->insertItem("checkbox");
  comboType->insertItem("radio");
  comboType->insertItem("submit");
  comboType->insertItem("reset");
  comboType->insertItem("file");
  comboType->insertItem("hidden");
  comboType->insertItem("image");
  comboType->insertItem("button");

  QLabel_2= new QLabel(this,"NoName");
  QLabel_2->setGeometry(10,40,90,30);
  QLabel_2->setMinimumSize(0,0);
  QLabel_2->setText(i18n("Name:"));

  lineName= new QLineEdit(this,"NoName");
  lineName->setGeometry(100,40,290,25);
  lineName->setMinimumSize(0,0);

  QLabel_3= new QLabel(this,"NoName");
  QLabel_3->setGeometry(10,70,90,30);
  QLabel_3->setMinimumSize(0,0);
  QLabel_3->setText(i18n("Value"));

  lineValue= new QLineEdit(this,"NoName");
  lineValue->setGeometry(100,70,290,25);
  lineValue->setMinimumSize(0,0);

  QLabel_4= new QLabel(this,"NoName");
  QLabel_4->setGeometry(10,100,90,30);
  QLabel_4->setMinimumSize(0,0);
  QLabel_4->setText(i18n("Size"));

  lineSize= new QLineEdit(this,"NoName");
  lineSize->setGeometry(100,100,80,25);
  lineSize->setMinimumSize(0,0);

  QLabel_5= new QLabel(this,"NoName");
  QLabel_5->setGeometry(190,100,90,30);
  QLabel_5->setMinimumSize(0,0);
  QLabel_5->setText(i18n("Max Len :"));

  lineMaxLen= new QLineEdit(this,"NoName");
  lineMaxLen->setGeometry(280,100,110,25);
  lineMaxLen->setMinimumSize(0,0);

  QLabel_6= new QLabel(this,"NoName");
  QLabel_6->setGeometry(10,130,90,30);
  QLabel_6->setMinimumSize(0,0);
  QLabel_6->setText(i18n("Image src"));

  lineSrc= new QLineEdit(this,"NoName");
  lineSrc->setGeometry(100,130,250,25);
  lineSrc->setMinimumSize(0,0);

  buttonSrc= new QPushButton(this,"NoName");
  buttonSrc->setGeometry(360,130,25,25);
  buttonSrc->setMinimumSize(0,0);
  buttonSrc->setText(i18n("..."));

  QLabel_7= new QLabel(this,"NoName");
  QLabel_7->setGeometry(10,160,90,30);
  QLabel_7->setMinimumSize(0,0);
  QLabel_7->setText(i18n("Alt  text :"));

  lineAlt= new QLineEdit(this,"NoName");
  lineAlt->setGeometry(100,160,290,25);
  lineAlt->setMinimumSize(0,0);

  QLabel_8= new QLabel(this,"NoName");
  QLabel_8->setGeometry(10,190,90,30);
  QLabel_8->setMinimumSize(0,0);
  QLabel_8->setText(i18n("Align:"));

  comboAlign= new QComboBox(true,this,"NoName");
  comboAlign->setGeometry(100,190,120,25);
  comboAlign->setMinimumSize(0,0);
  comboAlign->insertItem("");
  comboAlign->insertItem("top");
  comboAlign->insertItem("middle");
  comboAlign->insertItem("bottom");
  comboAlign->insertItem("left");
  comboAlign->insertItem("right");

  checkCheck= new QCheckBox(this,"NoName");
  checkCheck->setGeometry(10,220,100,30);
  checkCheck->setMinimumSize(0,0);
  checkCheck->setText(i18n("Checked"));

  checkReadOnly= new QCheckBox(this,"NoName");
  checkReadOnly->setGeometry(130,220,110,30);
  checkReadOnly->setMinimumSize(0,0);
  checkReadOnly->setText(i18n("Read only"));

  checkDisabled= new QCheckBox(this,"NoName");
  checkDisabled->setGeometry(260,220,100,30);
  checkDisabled->setMinimumSize(0,0);
  checkDisabled->setText(i18n("Disabled"));

  QLabel_9= new QLabel(this,"NoName");
  QLabel_9->setGeometry(10,250,90,30);
  QLabel_9->setMinimumSize(0,0);
  QLabel_9->setText(i18n("On Focus:"));

  lineOnFocus= new QLineEdit(this,"NoName");
  lineOnFocus->setGeometry(100,250,100,25);
  lineOnFocus->setMinimumSize(0,0);

  QLabel_10= new QLabel(this,"NoName");
  QLabel_10->setGeometry(200,250,90,30);
  QLabel_10->setMinimumSize(0,0);
  QLabel_10->setText(i18n("  On Blur:"));

  lineOnBlur= new QLineEdit(this,"NoName");
  lineOnBlur->setGeometry(290,250,100,25);
  lineOnBlur->setMinimumSize(0,0);

  QLabel_11= new QLabel(this,"NoName");
  QLabel_11->setGeometry(10,280,90,30);
  QLabel_11->setMinimumSize(0,0);
  QLabel_11->setText(i18n("On Select:"));

  lineOnSelect= new QLineEdit(this,"NoName");
  lineOnSelect->setGeometry(100,280,100,25);
  lineOnSelect->setMinimumSize(0,0);

  QLabel_12= new QLabel(this,"NoName");
  QLabel_12->setGeometry(200,280,90,30);
  QLabel_12->setMinimumSize(0,0);
  QLabel_12->setText(i18n(" On Change"));

  lineOnChange= new QLineEdit(this,"NoName");
  lineOnChange->setGeometry(290,280,100,25);
  lineOnChange->setMinimumSize(0,0);

}
