/**********************************************************************
            --- KDevelop (KDlgEdit)  generated file ---                

            Last generated: Sat Apr 1 04:00:29 2000

            DO NOT EDIT!!!  This file will be automatically
            regenerated by KDevelop.  All changes will be lost.

**********************************************************************/
#include <stdio.h>
#include <kapp.h>
#include <klocale.h>
#include "tagfontdlg.h"

void  TagFontDlg::initDialog(){
  this->resize(400,120);
  this->setMinimumSize(0,0);
  QLabel_1= new QLabel(this,"NoName");
  QLabel_1->setGeometry(10,10,100,30);
  QLabel_1->setMinimumSize(0,0);
  QLabel_1->setText(i18n("Size"));

  comboIncDec= new QComboBox(true,this,"NoName");
  comboIncDec->setGeometry(110,10,80,25);
  comboIncDec->setMinimumSize(0,0);

  QLabel_3= new QLabel(this,"NoName");
  QLabel_3->setGeometry(10,40,100,30);
  QLabel_3->setMinimumSize(0,0);
  QLabel_3->setText(i18n("Color"));

  comboColor= new QComboBox(true,this,"NoName");
  comboColor->setGeometry(110,40,140,25);
  comboColor->setMinimumSize(0,0);

  colorButton= new KColorButton(this,"NoName");
  colorButton->setGeometry(250,40,50,25);
  colorButton->setMinimumSize(0,0);
  colorButton->setText(i18n("Button"));

  QLabel_4= new QLabel(this,"NoName");
  QLabel_4->setGeometry(10,70,100,30);
  QLabel_4->setMinimumSize(0,0);
  QLabel_4->setText(i18n("Font"));

  comboFont= new QComboBox(true,this,"NoName");
  comboFont->setGeometry(110,70,280,25);
  comboFont->setMinimumSize(0,0);
  comboFont->insertItem("");
  comboFont->insertItem("serif");
  comboFont->insertItem("sans-serif");
  comboFont->insertItem("cursive");
  comboFont->insertItem("fantasy");
  comboFont->insertItem("monospace");

}
