/**********************************************************************
            --- KDevelop (KDlgEdit)  generated file ---                

            Last generated: Sun Apr 2 02:44:31 2000

            DO NOT EDIT!!!  This file will be automatically
            regenerated by KDevelop.  All changes will be lost.

**********************************************************************/
#include <kapp.h>
#include <klocale.h>
#include "tagformbutton.h"

void  TagFormButton::initDialog(){
  this->resize(400,140);
  this->setMinimumSize(0,0);
  QLabel_1= new QLabel(this,"NoName");
  QLabel_1->setGeometry(10,10,120,30);
  QLabel_1->setMinimumSize(0,0);
  QLabel_1->setText(i18n("Name:"));

  lineName= new QLineEdit(this,"NoName");
  lineName->setGeometry(130,10,260,25);
  lineName->setMinimumSize(0,0);

  QLabel_2= new QLabel(this,"NoName");
  QLabel_2->setGeometry(10,40,120,30);
  QLabel_2->setMinimumSize(0,0);
  QLabel_2->setText(i18n("Value:"));

  lineValue= new QLineEdit(this,"NoName");
  lineValue->setGeometry(130,40,260,25);
  lineValue->setMinimumSize(0,0);

  checkChecked= new QCheckBox(this,"NoName");
  checkChecked->setGeometry(10,100,380,30);
  checkChecked->setMinimumSize(0,0);
  checkChecked->setText(i18n("Checked"));

}
