/**********************************************************************
            --- KDevelop (KDlgEdit)  generated file ---                

            Last generated: Sun Apr 2 02:38:08 2000

            DO NOT EDIT!!!  This file will be automatically
            regenerated by KDevelop.  All changes will be lost.

**********************************************************************/
#include <kapp.h>
#include <klocale.h>
#include "tagform.h"

void  TagForm::initDialog(){
  this->resize(400,110);
  this->setMinimumSize(0,0);
  QLabel_1= new QLabel(this,"NoName");
  QLabel_1->setGeometry(10,10,90,30);
  QLabel_1->setMinimumSize(0,0);
  QLabel_1->setText(i18n("Action:"));

  lineAction= new KLineEdit(this,"NoName");
  lineAction->setGeometry(100,10,290,25);
  lineAction->setMinimumSize(0,0);

  QLabel_2= new QLabel(this,"NoName");
  QLabel_2->setGeometry(10,40,90,30);
  QLabel_2->setMinimumSize(0,0);
  QLabel_2->setText(i18n("Method:"));

  comboMethod= new QComboBox(true,this,"NoName");
  comboMethod->setGeometry(100,40,70,25);
  comboMethod->setMinimumSize(0,0);
  comboMethod->insertItem("get");
  comboMethod->insertItem("post");

  QLabel_3= new QLabel(this,"NoName");
  QLabel_3->setGeometry(10,70,90,30);
  QLabel_3->setMinimumSize(0,0);
  QLabel_3->setText(i18n("Enctype:"));

  comboEnctype= new QComboBox(true,this,"NoName");
  comboEnctype->setGeometry(100,70,290,25);
  comboEnctype->setMinimumSize(0,0);
  comboEnctype->insertItem("");
  comboEnctype->insertItem("application/x-www-form-urlencoded");
  comboEnctype->insertItem("multipart/form-data");

  QLabel_4= new QLabel(this,"NoName");
  QLabel_4->setGeometry(180,40,80,30);
  QLabel_4->setMinimumSize(0,0);
  QLabel_4->setText(i18n("Target:"));

  comboTarget= new QComboBox(true,this,"NoName");
  comboTarget->setGeometry(260,40,130,25);
  comboTarget->setMinimumSize(0,0);
  comboTarget->insertItem("");
  comboTarget->insertItem("_blank");
  comboTarget->insertItem("_self");
  comboTarget->insertItem("_parent");
  comboTarget->insertItem("_top");

}
