/**********************************************************************
            --- KDevelop (KDlgEdit)  generated file ---                

            Last generated: Tue Nov 30 22:48:40 1999

            DO NOT EDIT!!!  This file will be automatically
            regenerated by KDevelop.  All changes will be lost.

**********************************************************************/
#include <kapp.h>
#include <klocale.h>
#include "tagmaildlg.h"

void  TagMailDlg::initDialog()
{
  this->resize(390,90);

  comboBoxMail= new QComboBox(true,this,"comboBoxMail");
  comboBoxMail->setGeometry(90,10,280,25);
  comboBoxMail->setMinimumSize(0,0);

  QPushButtonCancel= new QPushButton(this,"buttonCancel");
  QPushButtonCancel->setGeometry(200,50,100,30);
  QPushButtonCancel->setMinimumSize(0,0);
  QPushButtonCancel->setText(i18n("Cancel"));

  QLabel_1= new QLabel(this,"labelMail");
  QLabel_1->setGeometry(10,10,70,30);
  QLabel_1->setMinimumSize(0,0);
  QLabel_1->setText(i18n("E-Mail"));

  QPushButtonOk= new QPushButton(this,"buttonOk");
  QPushButtonOk->setGeometry(90,50,100,30);
  QPushButtonOk->setMinimumSize(0,0);
  QPushButtonOk->setText(i18n("Ok"));
  QPushButtonOk->setDefault(true);

}
