/**********************************************************************
            --- KDevelop (KDlgEdit)  generated file ---                

            Last generated: Tue Nov 30 22:50:20 1999

            DO NOT EDIT!!!  This file will be automatically
            regenerated by KDevelop.  All changes will be lost.

**********************************************************************/
#include <kapp.h>
#include <klocale.h>
#include <qtooltip.h>
#include "tagquickstart.h"

extern const char *colorsList[];

void  TagQuickStart::initDialog()
{
	this->resize(430,280);

  labelTitle= new QLabel(this,"labelTitle");
  labelTitle->setGeometry(10,10,110,30);
  labelTitle->setMinimumSize(0,0);
  labelTitle->setText(i18n("Title"));

  labelBGImage= new QLabel(this,"labelBGImage");
  labelBGImage->setGeometry(10,40,110,30);
  labelBGImage->setMinimumSize(0,0);
  labelBGImage->setText(i18n("BG Image"));

  labelBGColor= new QLabel(this,"labelBGColor");
  labelBGColor->setGeometry(10,70,160,30);
  labelBGColor->setMinimumSize(0,0);
  labelBGColor->setText(i18n("BG Color"));

  labelTextColor= new QLabel(this,"labelTextColor");
  labelTextColor->setGeometry(10,100,160,30);
  labelTextColor->setMinimumSize(0,0);
  labelTextColor->setText(i18n("Text Color"));

  labelActiveLinkColor= new QLabel(this,"labelActiveLinkColor");
  labelActiveLinkColor->setGeometry(10,160,160,30);
  labelActiveLinkColor->setMinimumSize(0,0);
  labelActiveLinkColor->setText(i18n("Active Link Color"));

  lineTitle= new QLineEdit(this,"NoName");
  lineTitle->setGeometry(120,10,290,25);
  lineTitle->setMinimumSize(0,0);

  lineBGImage= new QLineEdit(this,"NoName");
  lineBGImage->setGeometry(120,40,245,25);
  lineBGImage->setMinimumSize(0,0);

  buttonFileSelect= new QPushButton(this,"NoName");
  buttonFileSelect->setGeometry(370,40,40,25);
  buttonFileSelect->setMinimumSize(0,0);
  QToolTip::add(buttonFileSelect,i18n("Select background image"));
  buttonFileSelect->setText(i18n("..."));

  comboBGColor= new QComboBox(true,this,"NoName");
  comboBGColor->setGeometry(170,70,190,25);
  comboBGColor->setMinimumSize(0,0);
  comboBGColor->insertStrList( colorsList );

  cButtonBGColor= new KColorButton(QColor("#FFFFFF"),this,"NoName");
  cButtonBGColor->setGeometry(370,70,40,25);
  cButtonBGColor->setMinimumSize(0,0);
  cButtonBGColor->setText(i18n("Button"));

  comboTextColor= new QComboBox(true,this,"NoName");
  comboTextColor->setGeometry(170,100,190,25);
  comboTextColor->setMinimumSize(0,0);
  comboTextColor->insertStrList( colorsList );

  cButtonTextColor= new KColorButton(this,"NoName");
  cButtonTextColor->setGeometry(370,100,40,25);
  cButtonTextColor->setMinimumSize(0,0);
  cButtonTextColor->setText(i18n("Button"));

  comboLinkColor= new QComboBox(true,this,"NoName");
  comboLinkColor->setGeometry(170,130,190,25);
  comboLinkColor->setMinimumSize(0,0);
  comboLinkColor->insertStrList( colorsList );

  cButtonLinkColor= new KColorButton(this,"NoName");
  cButtonLinkColor->setGeometry(370,130,40,25);
  cButtonLinkColor->setMinimumSize(0,0);
  cButtonLinkColor->setText(i18n("Button"));

  comboALinkColor= new QComboBox(true,this,"NoName");
  comboALinkColor->setGeometry(170,160,190,25);
  comboALinkColor->setMinimumSize(0,0);
  comboALinkColor->insertStrList( colorsList );

  cButtonALinkColor= new KColorButton(this,"NoName");
  cButtonALinkColor->setGeometry(370,160,40,25);
  cButtonALinkColor->setMinimumSize(0,0);
  cButtonALinkColor->setText(i18n("Button"));

  QLabel_8= new QLabel(this,"NoName");
  QLabel_8->setGeometry(10,190,160,30);
  QLabel_8->setMinimumSize(0,0);
  QLabel_8->setText(i18n("Visited Link Color"));

  comboVLinkColor= new QComboBox(true,this,"NoName");
  comboVLinkColor->setGeometry(170,190,190,25);
  comboVLinkColor->setMinimumSize(0,0);
  comboVLinkColor->insertStrList( colorsList );

  cButtonVLinkColor= new KColorButton(this,"NoName");
  cButtonVLinkColor->setGeometry(370,190,40,25);
  cButtonVLinkColor->setMinimumSize(0,0);
  cButtonVLinkColor->setText(i18n("Button"));

  QLabel_7= new QLabel(this,"NoName");
  QLabel_7->setGeometry(10,130,160,30);
  QLabel_7->setMinimumSize(0,0);
  QLabel_7->setText(i18n("Link Color"));

  buttonOk= new QPushButton(this,"");
  buttonOk->setGeometry(80,230,100,30);
  buttonOk->setMinimumSize(0,0);
  buttonOk->setText(i18n("Ok"));
  buttonOk->setDefault(true);

  buttonCancel= new QPushButton(this,"");
  buttonCancel->setGeometry(240,230,100,30);
  buttonCancel->setMinimumSize(0,0);
  buttonCancel->setText(i18n("Cancel"));

}
