/**********************************************************************
            --- KDevelop (KDlgEdit)  generated file ---                

            Last generated: Tue Nov 30 17:49:01 1999

            DO NOT EDIT!!!  This file will be automatically
            regenerated by KDevelop.  All changes will be lost.

**********************************************************************/
#include <kapp.h>
#include <klocale.h>
#include "tagquicktable.h"

void  TagQuickTable::initDialog()
{
	this->resize(230,120);
  this->setMinimumSize(0,0);
  spinBoxRows= new QSpinBox(this,"NoName");
  spinBoxRows->setGeometry(120,10,100,25);
  spinBoxRows->setMinimumSize(0,0);
  spinBoxRows->setRange(1,99);

  spinBoxCollums= new QSpinBox(this,"NoName");
  spinBoxCollums->setGeometry(120,40,100,25);
  spinBoxCollums->setMinimumSize(0,0);
  spinBoxCollums->setRange(0,99);

  QLabel_1= new QLabel(this,"NoName");
  QLabel_1->setGeometry(10,10,100,30);
  QLabel_1->setMinimumSize(0,0);
  QLabel_1->setText(i18n("Num of Rows"));

  QLabel_2= new QLabel(this,"NoName");
  QLabel_2->setGeometry(10,40,100,30);
  QLabel_2->setMinimumSize(0,0);
  QLabel_2->setText(i18n("Num of Collums"));

  buttonOk= new QPushButton(this,"NoName");
  buttonOk->setGeometry(10,80,100,30);
  buttonOk->setMinimumSize(0,0);
  buttonOk->setText(i18n("Ok"));
  buttonOk->setDefault(true);

  buttonCancel= new QPushButton(this,"NoName");
  buttonCancel->setGeometry(120,80,100,30);
  buttonCancel->setMinimumSize(0,0);
  buttonCancel->setText(i18n("Cancel"));

}
