/**********************************************************************
            --- KDevelop (KDlgEdit)  generated file ---                

            Last generated: Sun Apr 2 03:33:53 2000

            DO NOT EDIT!!!  This file will be automatically
            regenerated by KDevelop.  All changes will be lost.

**********************************************************************/
#include <kapp.h>
#include <klocale.h>
#include "tagtabledlg.h"

void  TagTableDlg::initDialog(){
  this->resize(400,200);
  this->setMinimumSize(0,0);
  QLabel_1= new QLabel(this,"NoName");
  QLabel_1->setGeometry(210,40,120,30);
  QLabel_1->setMinimumSize(0,0);
  QLabel_1->setText(i18n("Cell Padding"));

  lineWidth= new KLineEdit(this,"NoName");
  lineWidth->setGeometry(130,10,60,25);
  lineWidth->setMinimumSize(0,0);

  lineBorder= new KLineEdit(this,"NoName");
  lineBorder->setGeometry(130,40,60,25);
  lineBorder->setMinimumSize(0,0);

  lineCellSpacing= new KLineEdit(this,"NoName");
  lineCellSpacing->setGeometry(330,10,60,25);
  lineCellSpacing->setMinimumSize(0,0);

  lineCellPadding= new KLineEdit(this,"NoName");
  lineCellPadding->setGeometry(330,40,60,25);
  lineCellPadding->setMinimumSize(0,0);

  QLabel_2= new QLabel(this,"NoName");
  QLabel_2->setGeometry(10,70,120,30);
  QLabel_2->setMinimumSize(0,0);
  QLabel_2->setText(i18n("Align"));

  comboAlign= new QComboBox(true,this,"NoName");
  comboAlign->setGeometry(130,70,230,25);
  comboAlign->setMinimumSize(0,0);

  QLabel_3= new QLabel(this,"NoName");
  QLabel_3->setGeometry(10,10,120,30);
  QLabel_3->setMinimumSize(0,0);
  QLabel_3->setText(i18n("Width"));

  QLabel_4= new QLabel(this,"NoName");
  QLabel_4->setGeometry(210,10,120,30);
  QLabel_4->setMinimumSize(0,0);
  QLabel_4->setText(i18n("Cell Spacing"));

  QLabel_6= new QLabel(this,"NoName");
  QLabel_6->setGeometry(10,40,120,30);
  QLabel_6->setMinimumSize(0,0);
  QLabel_6->setText(i18n("Border"));

  QLabel_7= new QLabel(this,"NoName");
  QLabel_7->setGeometry(10,160,120,30);
  QLabel_7->setMinimumSize(0,0);
  QLabel_7->setText(i18n("BG Color"));

  comboBGColor= new QComboBox(true,this,"NoName");
  comboBGColor->setGeometry(130,160,160,25);
  comboBGColor->setMinimumSize(0,0);

  colorButton= new KColorButton(this,"NoName");
  colorButton->setGeometry(300,160,60,25);
  colorButton->setMinimumSize(0,0);
  colorButton->setText(i18n("Button"));

}
