/**********************************************************************
            --- KDevelop (KDlgEdit)  generated file ---                

            Last generated: Sun Apr 2 02:29:40 2000

            DO NOT EDIT!!!  This file will be automatically
            regenerated by KDevelop.  All changes will be lost.

**********************************************************************/
#include <kapp.h>
#include <klocale.h>
#include "tagtablehead.h"

void  TagTableHead::initDialog()
{
  this->resize(400,230);
  this->setMinimumSize(0,0);
	
  QLabel_1= new QLabel(this,"NoName");
  QLabel_1->setGeometry(10,10,110,30);
  QLabel_1->setMinimumSize(0,0);
  QLabel_1->setText(i18n("Width"));

  lineWidth= new KLineEdit(this,"NoName");
  lineWidth->setGeometry(120,10,80,25);
  lineWidth->setMinimumSize(0,0);

	lineHeight= new KLineEdit(this,"NoName");
  lineHeight->setGeometry(120,40,80,25);
  lineHeight->setMinimumSize(0,0);

  lineColSpan= new KLineEdit(this,"NoName");
  lineColSpan->setGeometry(310,10,80,25);
  lineColSpan->setMinimumSize(0,0); 
	
	lineRowSpan= new KLineEdit(this,"NoName");
  lineRowSpan->setGeometry(310,40,80,25);
  lineRowSpan->setMinimumSize(0,0);

  QLabel_2= new QLabel(this,"NoName");
  QLabel_2->setGeometry(10,100,110,30);
  QLabel_2->setMinimumSize(0,0);
  QLabel_2->setText(i18n("Align"));

  comboAlign= new QComboBox(true,this,"NoName");
  comboAlign->setGeometry(120,100,190,25);
  comboAlign->setMinimumSize(0,0);

  QLabel_3= new QLabel(this,"NoName");
  QLabel_3->setGeometry(210,10,100,30);
  QLabel_3->setMinimumSize(0,0);
  QLabel_3->setText(i18n("Col Span"));

  QLabel_4= new QLabel(this,"NoName");
  QLabel_4->setGeometry(10,40,110,30);
  QLabel_4->setMinimumSize(0,0);
  QLabel_4->setText(i18n("Height"));

  QLabel_5= new QLabel(this,"NoName");
  QLabel_5->setGeometry(10,130,110,30);
  QLabel_5->setMinimumSize(0,0);
  QLabel_5->setText(i18n("VAlign"));

  comboVAlign= new QComboBox(true,this,"NoName");
  comboVAlign->setGeometry(120,130,190,25);
  comboVAlign->setMinimumSize(0,0);

  QLabel_6= new QLabel(this,"NoName");
  QLabel_6->setGeometry(210,40,100,30);
  QLabel_6->setMinimumSize(0,0);
  QLabel_6->setText(i18n("Row Span"));

  QLabel_7= new QLabel(this,"NoName");
  QLabel_7->setGeometry(10,190,110,30);
  QLabel_7->setMinimumSize(0,0);
  QLabel_7->setText(i18n("BG Color"));

  comboBGColor= new QComboBox(true,this,"NoName");
  comboBGColor->setGeometry(120,190,160,25);
  comboBGColor->setMinimumSize(0,0);

  colorButton= new KColorButton(this,"NoName");
  colorButton->setGeometry(290,190,95,25);
  colorButton->setMinimumSize(0,0);
  colorButton->setText(i18n("Button"));

}
