/***************************************************************************
                          quantadoc.h  -  description
                             -------------------
    begin                : Втр Май  9 13:29:57 EEST 2000
    copyright            : (C) 2000 by Dmitry Poplavsky & Alexander Yakovlev & Eric Laffoon
    email                : pdima@users.sourceforge.net,yshurik@linuxfan.com,sequitur@easystreet.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/

#ifndef QUANTADOC_H
#define QUANTADOC_H

#ifdef HAVE_CONFIG_H
#include <config.h>
#endif 

// include files for QT
#include <qlist.h>
#include <qdict.h>
#include <qobject.h>
#include <qstring.h>

#include <kurl.h>

// forward declaration of the Quanta classes
class QuantaApp;
class QuantaView;
class Document;

class QPopupMenu;
class KPopupMenu;

class KConfig;
class KWriteManager;

/**	QuantaDoc provides a document object for a document-view model.
  *
  * The QuantaDoc class provides a document object that can be used in
  * conjunction with the classes QuantaApp and QuantaView to create a
  * document-view model for standard KDE applications based on
  * KApplication and KTMainWindow. Thereby, the document object is
  * created by the QuantaApp instance and contains the document
  * structure with the according methods for manipulation of the
  * document data by QuantaView objects. Also, QuantaDoc contains the
  * methods for serialization of the document data from and to files.
  *
  * @author Source Framework Automatically Generated by KDevelop, (c) The KDevelop Team. 	
  * @version KDevelop version 0.4 code generation */
class QuantaDoc : public QObject
{
  Q_OBJECT

  friend class QuantaApp;
  friend class QuantaView;

  public:
    
    QuantaDoc( QuantaApp *app, QWidget *parent, const char *name=0);
    ~QuantaDoc();
    
    void openDocument (const KURL&);
    void saveDocument (const KURL&);
    void closeDocument();    
        
    void prevDocument();
    void nextDocument();
    
    KURL    url();
		QString basePath();
    
    bool isModified();
    bool isModifiedAll();
    void setModified(bool flag = true);
    
    /// "save modified" - asks the user 
    /// for saving if the document is modified
    bool saveModified();	
    bool saveAll(bool dont_ask=true);

    Document *write();
		
		// for kwrites
		void  readConfig( KConfig * );
		void writeConfig( KConfig * );
		
		/** set RB menu for KWrite */
		void setRBMenu( QPopupMenu * rbMenu ) { this->rbMenu = rbMenu; }

  private:
    bool newDocument (const KURL&);
    void changeFileTabName(QString);
    Document *newWrite(QWidget *parent);
	
  public slots:
    /** close documents. */
    void closeAll();

    /** show popup menu with list of attributes for current tag */
    void slotInsertAttrib      ( int id );
    void slotInsertCoreAttrib  ( int id );
    void slotInsertEventsAttrib( int id );
    void slotAttribPopup();
    
    void editorOptions();
    
    void cut();
    void copy();
    void paste();
    void undo();
    void redo();
    void undoHistory();
    void selectAll();
    void deselectAll();
    void find();
    void findAgain();
    void replace();
    void invertSelect();
    void verticalSelect();

 	
  signals:
    void title(QString);
  	void openedFiles(QStringList);

  private:
  	
  	QuantaApp *app;
    /** list with documents( kwrites ) */
    QDict<Document> *docList;
    /** manager for bookmarks */
    KWriteManager *writeManager;
    QPopupMenu *rbMenu;

    KPopupMenu *attribMenu;
    QPopupMenu *attribCoreMenu;
    QPopupMenu *attribEventsMenu;
};

#endif // QUANTADOC_H
