/**********************************************************************
            --- KDevelop (KDlgEdit)  generated file ---                

            Last generated: Thu Apr 13 00:54:02 2000

            DO NOT EDIT!!!  This file will be automatically
            regenerated by KDevelop.  All changes will be lost.

**********************************************************************/
#include <kapp.h>
#include "toolbarscriptconfigure.h"

void  ToolbarScriptConfigure::initDialog(){
  this->resize(400,400);
  this->setMinimumSize(0,0);
  QLabel_1= new QLabel(this,"NoName");
  QLabel_1->setGeometry(10,10,380,30);
  QLabel_1->setMinimumSize(0,0);
  QLabel_1->setText(i18n("INPUT (stdin) :"));

  groupInput= new QButtonGroup(this,"NoName");
  groupInput->setGeometry(10,40,380,110);
  groupInput->setMinimumSize(0,0);

  radioInputNone= new QRadioButton(groupInput,"NoName");
  radioInputNone->setGeometry(10,10,360,30);
  radioInputNone->setMinimumSize(0,0);
  radioInputNone->setText(i18n("None"));
  radioInputNone->setChecked(true);

  radioSelectedText= new QRadioButton(groupInput,"NoName");
  radioSelectedText->setGeometry(10,40,360,30);
  radioSelectedText->setMinimumSize(0,0);
  radioSelectedText->setText(i18n("Selected text"));

  radioCurrentDoc= new QRadioButton(groupInput,"NoName");
  radioCurrentDoc->setGeometry(10,70,360,30);
  radioCurrentDoc->setMinimumSize(0,0);
  radioCurrentDoc->setText(i18n("Current document"));

  QLabel_2= new QLabel(this,"NoName");
  QLabel_2->setGeometry(10,150,380,30);
  QLabel_2->setMinimumSize(0,0);
  QLabel_2->setText(i18n("OUTPUT (stdout) :"));

  groupOutput= new QButtonGroup(this,"NoName");
  groupOutput->setGeometry(10,180,380,170);
  groupOutput->setMinimumSize(0,0);

  radioOutputNone= new QRadioButton(groupOutput,"NoName");
  radioOutputNone->setGeometry(10,10,360,30);
  radioOutputNone->setMinimumSize(0,0);
  radioOutputNone->setText(i18n("None"));
  radioOutputNone->setChecked(true);

  radioInsInCurPos= new QRadioButton(groupOutput,"NoName");
  radioInsInCurPos->setGeometry(10,40,360,30);
  radioInsInCurPos->setMinimumSize(0,0);
  radioInsInCurPos->setText(i18n("Insert in cursor position"));

  radioReplaceCurDoc= new QRadioButton(groupOutput,"NoName");
  radioReplaceCurDoc->setGeometry(10,70,360,30);
  radioReplaceCurDoc->setMinimumSize(0,0);
  radioReplaceCurDoc->setText(i18n("Replace current document"));

  radioCreateNewDoc= new QRadioButton(groupOutput,"NoName");
  radioCreateNewDoc->setGeometry(10,100,360,30);
  radioCreateNewDoc->setMinimumSize(0,0);
  radioCreateNewDoc->setText(i18n("Create new document"));

  radioInMesWindow= new QRadioButton(groupOutput,"NoName");
  radioInMesWindow->setGeometry(10,130,360,30);
  radioInMesWindow->setMinimumSize(0,0);
  radioInMesWindow->setText(i18n("In Message window"));

  buttonOk= new QPushButton(this,"NoName");
  buttonOk->setGeometry(180,360,100,30);
  buttonOk->setMinimumSize(0,0);
  buttonOk->setText(i18n("Ok"));
  buttonOk->setDefault(true);
  buttonOk->setAutoDefault(true);

  buttonCancel= new QPushButton(this,"NoName");
  buttonCancel->setGeometry(290,360,100,30);
  buttonCancel->setMinimumSize(0,0);
  buttonCancel->setText(i18n("Cancel"));

}
