/**********************************************************************
            --- KDevelop (KDlgEdit)  generated file ---                

            Last generated: Sat Apr 8 23:30:02 2000

            DO NOT EDIT!!!  This file will be automatically
            regenerated by KDevelop.  All changes will be lost.

**********************************************************************/
#include <kapp.h>
#include "toolbarconfig.h"

void  ToolBarConfig::initDialog(){
  this->resize(550,360);
  this->setMinimumSize(0,0);
  list= new QListView(this,"NoName");
  list->setGeometry(10,10,220,240);
  list->setMinimumSize(0,0);

  buttonNew= new KButton(this,"NoName");
  buttonNew->setGeometry(20,260,40,30);
  buttonNew->setMinimumSize(0,0);
  buttonNew->setText(i18n("New"));

  buttonUp= new KButton(this,"NoName");
  buttonUp->setGeometry(70,260,40,30);
  buttonUp->setMinimumSize(0,0);
  buttonUp->setText(i18n("Up"));

  buttonDown= new KButton(this,"NoName");
  buttonDown->setGeometry(120,260,40,30);
  buttonDown->setMinimumSize(0,0);
  buttonDown->setText(i18n("Down"));

  buttonDel= new KButton(this,"NoName");
  buttonDel->setGeometry(170,260,40,30);
  buttonDel->setMinimumSize(0,0);
  buttonDel->setText(i18n("Del"));

  lineName= new QLineEdit(this,"NoName");
  lineName->setGeometry(310,10,230,25);
  lineName->setMinimumSize(0,0);

  checkSeparator= new QCheckBox(this,"NoName");
  checkSeparator->setGeometry(240,70,300,30);
  checkSeparator->setMinimumSize(0,0);
  checkSeparator->setText(i18n("Separator"));

  QLabel_1= new QLabel(this,"NoName");
  QLabel_1->setGeometry(240,10,70,30);
  QLabel_1->setMinimumSize(0,0);
  QLabel_1->setText(i18n("Name"));

  QLabel_2= new QLabel(this,"NoName");
  QLabel_2->setGeometry(240,40,70,30);
  QLabel_2->setMinimumSize(0,0);
  QLabel_2->setText(i18n("Icon"));

  lineIcon= new QLineEdit(this,"NoName");
  lineIcon->setGeometry(310,40,130,25);
  lineIcon->setMinimumSize(0,0);

  buttonIcon= new QPushButton(this,"NoName");
  buttonIcon->setGeometry(450,40,40,25);
  buttonIcon->setMinimumSize(0,0);
  buttonIcon->setText(i18n("..."));

  buttonKIconEdit= new QPushButton(this,"NoName");
  buttonKIconEdit->setGeometry(500,40,40,25);
  buttonKIconEdit->setMinimumSize(0,0);
  buttonKIconEdit->setText(i18n("..."));

  KSeparator_2= new KSeparator(this,"NoName");
  KSeparator_2->setGeometry(10,300,530,10);
  KSeparator_2->setMinimumSize(0,0);
  KSeparator_2->setOrientation(KSeparator::HLine);

  groupBox= new QButtonGroup(this,"NoName");
  groupBox->setGeometry(240,100,300,80);
  groupBox->setMinimumSize(0,0);

  radioInsertTag= new QRadioButton(this,"NoName");
  radioInsertTag->setGeometry(250,110,280,30);
  radioInsertTag->setMinimumSize(0,0);
  radioInsertTag->setText(i18n("Insert text (tag)"));
  radioInsertTag->setChecked(true);

  radioExecuteScript= new QRadioButton(this,"NoName");
  radioExecuteScript->setGeometry(250,140,280,30);
  radioExecuteScript->setMinimumSize(0,0);
  radioExecuteScript->setText(i18n("Execute external script"));

  QLabel_3= new QLabel(this,"NoName");
  QLabel_3->setGeometry(240,190,100,30);
  QLabel_3->setMinimumSize(0,0);
  QLabel_3->setText(i18n("<tag> :"));

  lineTag= new QLineEdit(this,"NoName");
  lineTag->setGeometry(340,190,200,25);
  lineTag->setMinimumSize(0,0);

  checkEndTag= new QCheckBox(this,"NoName");
  checkEndTag->setGeometry(240,220,100,30);
  checkEndTag->setMinimumSize(0,0);
  checkEndTag->setText(i18n("</tag> :"));

  lineEndTag= new QLineEdit(this,"NoName");
  lineEndTag->setGeometry(340,220,200,25);
  lineEndTag->setMinimumSize(0,0);

  QLabel_4= new QLabel(this,"NoName");
  QLabel_4->setGeometry(240,260,100,30);
  QLabel_4->setMinimumSize(0,0);
  QLabel_4->setText(i18n("Script:"));

  lineScript= new QLineEdit(this,"NoName");
  lineScript->setGeometry(340,260,150,25);
  lineScript->setMinimumSize(0,0);

  buttonConfigScript= new QPushButton(this,"NoName");
  buttonConfigScript->setGeometry(500,260,40,25);
  buttonConfigScript->setMinimumSize(0,0);
  buttonConfigScript->setText(i18n("..."));

  buttonOk= new QPushButton(this,"NoName");
  buttonOk->setGeometry(310,320,100,30);
  buttonOk->setMinimumSize(0,0);
  buttonOk->setText(i18n("Ok"));
  buttonOk->setDefault(true);
  buttonOk->setAutoDefault(true);

  buttonCancel= new QPushButton(this,"NoName");
  buttonCancel->setGeometry(430,320,100,30);
  buttonCancel->setMinimumSize(0,0);
  buttonCancel->setText(i18n("Cancel"));

}
