/**********************************************************************
            --- KDevelop (KDlgEdit)  generated file ---                

            DO NOT EDIT!!!  This file will be automatically
            regenerated by KDevelop.  All changes will be lost.

**********************************************************************/
#include <kapp.h>
#include <klocale.h>
#include "filesmask.h"

void  FilesMask::initDialog(){
  this->resize(400,330);
  this->setMinimumSize(400,330);
  QLabel_1= new QLabel(this,"NoName");
  QLabel_1->setGeometry(10,50,380,30);
  QLabel_1->setMinimumSize(0,0);
  QLabel_1->setText(i18n("HTML files:"));
/*
  QLabel_2= new QLabel(this,"NoName");
  QLabel_2->setGeometry(10,10,380,30);
  QLabel_2->setMinimumSize(0,0);
  QLabel_2->setText(i18n("Mask for:"));

  KSeparator_1= new KSeparator(this,"NoName");
  KSeparator_1->setGeometry(10,40,380,10);
  KSeparator_1->setMinimumSize(0,0);
  KSeparator_1->setOrientation(KSeparator::HLine);
*/
  QLabel_3= new QLabel(this,"NoName");
  QLabel_3->setGeometry(10,110,380,30);
  QLabel_3->setMinimumSize(0,0);
  QLabel_3->setText(i18n("PHP files:"));

  QLabel_4= new QLabel(this,"NoName");
  QLabel_4->setGeometry(10,170,380,30);
  QLabel_4->setMinimumSize(0,0);
  QLabel_4->setText(i18n("Images:"));

  QLabel_5= new QLabel(this,"NoName");
  QLabel_5->setGeometry(10,230,380,30);
  QLabel_5->setMinimumSize(0,0);
  QLabel_5->setText(i18n("Text fles:"));

  lineHTML= new QLineEdit(this,"NoName");
  lineHTML->setGeometry(10,80,380,25);
  lineHTML->setMinimumSize(0,0);

  linePHP= new QLineEdit(this,"NoName");
  linePHP->setGeometry(10,140,380,25);
  linePHP->setMinimumSize(0,0);

  lineImages= new QLineEdit(this,"NoName");
  lineImages->setGeometry(10,200,380,25);
  lineImages->setMinimumSize(0,0);

  lineText= new QLineEdit(this,"NoName");
  lineText->setGeometry(10,260,380,25);
  lineText->setMinimumSize(0,0);

  buttonDefault= new QPushButton(this,"NoName");
  buttonDefault->setGeometry(290,300,100,30);
  buttonDefault->setMinimumSize(0,0);
  buttonDefault->setText(i18n("Default"));

}
