/**********************************************************************
            --- KDevelop (KDlgEdit)  generated file ---                

            DO NOT EDIT!!!  This file will be automatically
            regenerated by KDevelop.  All changes will be lost.

**********************************************************************/
#include <kapp.h>
#include <klocale.h>
#include "previewoptions.h"

void  PreviewOptions::initDialog(){
  this->resize(400,300);
  this->setMinimumSize(0,0);
  groupPreviewPlace= new QButtonGroup(this,"NoName");
  groupPreviewPlace->setGeometry(10,10,200,140);
  groupPreviewPlace->setMinimumSize(0,0);

  radioBottom= new QRadioButton(groupPreviewPlace,"NoName");
  radioBottom->setGeometry(10,10,150,30);
  radioBottom->setMinimumSize(0,0);
  radioBottom->setText(i18n("Bottom"));

  radioRight= new QRadioButton(groupPreviewPlace,"");
  radioRight->setGeometry(10,40,150,30);
  radioRight->setMinimumSize(0,0);
  radioRight->setText(i18n("Right"));

  radioFullworkspace= new QRadioButton(groupPreviewPlace,"NoName");
  radioFullworkspace->setGeometry(10,70,150,30);
  radioFullworkspace->setMinimumSize(0,0);
  radioFullworkspace->setText(i18n("Full workspace"));

  radioDisabled= new QRadioButton(groupPreviewPlace,"NoName");
  radioDisabled->setGeometry(10,100,100,30);
  radioDisabled->setMinimumSize(0,0);
  radioDisabled->setText(i18n("Disabled"));

  illustration= new QWidget(this,"NoName");
  illustration->setGeometry(220,10,170,140);
  illustration->setMinimumSize(0,0);
}
