/**********************************************************************
            --- KDevelop (KDlgEdit)  generated file ---                

            Last generated: Fri Apr 7 02:27:29 2000

            DO NOT EDIT!!!  This file will be automatically
            regenerated by KDevelop.  All changes will be lost.

**********************************************************************/
#include <kapp.h>
#include <klocale.h>
#include "styleoptions.h"

void  StyleOptions::initDialog(){
  this->resize(395,320);
  this->setMinimumSize(395,320);
  checkTagsCapital= new QCheckBox(this,"NoName");
  checkTagsCapital->setGeometry(20,50,350,30);
  checkTagsCapital->setMinimumSize(0,0);
  checkTagsCapital->setText(i18n("Use capital symbols for tags"));

  checkAttrCapital= new QCheckBox(this,"NoName");
  checkAttrCapital->setGeometry(20,80,350,30);
  checkAttrCapital->setMinimumSize(0,0);
  checkAttrCapital->setText(i18n("Use capital symbols for attributes of tags"));
/*
  KSeparator_1= new KSeparator(this,"NoName");
  KSeparator_1->setGeometry(10,20,380,20);
  KSeparator_1->setMinimumSize(0,0);
  KSeparator_1->setOrientation(KSeparator::HLine);
*/
  KSeparator_2= new KSeparator(this,"NoName");
  KSeparator_2->setGeometry(10,110,380,30);
  KSeparator_2->setMinimumSize(0,0);
  KSeparator_2->setOrientation(KSeparator::HLine);

  checkEndTag= new QCheckBox(this,"NoName");
  checkEndTag->setGeometry(20,140,350,30);
  checkEndTag->setMinimumSize(0,0);
  checkEndTag->setText(i18n("Insert end of tag if optional"));
  checkEndTag->setChecked(true);

}
