/**********************************************************************
            --- KDevelop (KDlgEdit)  generated file ---                

            Last generated: Mon Mar 27 20:27:40 2000

            DO NOT EDIT!!!  This file will be automatically
            regenerated by KDevelop.  All changes will be lost.

**********************************************************************/
#include <klocale.h>
#include "copyto.h"

void  CopyTo::initDialog(){
  this->setMinimumSize(0,0);
  lineDir= new QLineEdit(this,"NoName");
  lineDir->setGeometry(10,10,300,30);
  lineDir->setMinimumSize(0,0);
  lineDir->setFocus();

  buttonDir= new QPushButton(this,"NoName");
  buttonDir->setGeometry(320,10,30,30);
  buttonDir->setMinimumSize(0,0);
  buttonDir->setText(i18n("..."));

  buttonOk= new QPushButton(this,"NoName");
  buttonOk->setGeometry(140,50,100,30);
  buttonOk->setMinimumSize(0,0);
  buttonOk->setText(i18n("Ok"));
  buttonOk->setDefault(true);
  buttonOk->setAutoDefault(true);

  buttonCancel= new QPushButton(this,"NoName");
  buttonCancel->setGeometry(250,50,100,30);
  buttonCancel->setMinimumSize(0,0);
  buttonCancel->setText(i18n("Cancel"));

}
