/**********************************************************************
            --- KDevelop (KDlgEdit)  generated file ---                

            DO NOT EDIT!!!  This file will be automatically
            regenerated by KDevelop.  All changes will be lost.

**********************************************************************/
#include <kapp.h>
#include <klocale.h>
#include "projectnewgetfiles.h"

void  ProjectNewGetFiles::initDialog(){
  this->resize(450,370);
  this->setMinimumSize(0,0);
  QLabel_1= new QLabel(this,"NoName");
  QLabel_1->setGeometry(10,10,430,30);
  QLabel_1->setMinimumSize(0,0);
  QLabel_1->setText(i18n("Insert local files"));

  QButtonGroup_1= new QButtonGroup(this,"NoName");
  QButtonGroup_1->setGeometry(10,40,430,110);
  QButtonGroup_1->setMinimumSize(0,0);

  checkInsertFiles= new QCheckBox(QButtonGroup_1,"NoName");
  checkInsertFiles->setGeometry(10,10,410,30);
  checkInsertFiles->setMinimumSize(0,0);
  checkInsertFiles->setText(i18n("Insert files from directory to project"));
  checkInsertFiles->setChecked(false);

  checkWebFiles= new QCheckBox(QButtonGroup_1,"NoName");
  checkWebFiles->setGeometry(10,40,410,30);
  checkWebFiles->setMinimumSize(0,0);
  checkWebFiles->setText(i18n("Insert only web files and images."));
  checkWebFiles->setChecked(true);

  QLabel_6= new QLabel(QButtonGroup_1,"NoName");
  QLabel_6->setGeometry(10,70,100,30);
  QLabel_6->setMinimumSize(0,0);
  QLabel_6->setText(i18n("Files Mask:"));

  lineFilesMask= new KLineEdit(QButtonGroup_1,"NoName");
  lineFilesMask->setGeometry(110,70,310,25);
  lineFilesMask->setMinimumSize(0,0);

  QLabel_2= new QLabel(this,"NoName");
  QLabel_2->setGeometry(10,190,430,30);
  QLabel_2->setMinimumSize(0,0);
  QLabel_2->setText(i18n("Insert remote files ( wget options )"));

  QButtonGroup_2= new QButtonGroup(this,"NoName");
  QButtonGroup_2->setGeometry(10,220,430,110);
  QButtonGroup_2->setMinimumSize(0,0);

  QLabel_3= new QLabel(QButtonGroup_2,"NoName");
  QLabel_3->setGeometry(10,10,100,30);
  QLabel_3->setMinimumSize(0,0);
  QLabel_3->setText(i18n("Site URL:"));

  lineSiteUrl= new KLineEdit(QButtonGroup_2,"NoName");
  lineSiteUrl->setGeometry(110,10,310,25);
  lineSiteUrl->setMinimumSize(0,0);

  QLabel_4= new QLabel(QButtonGroup_2,"NoName");
  QLabel_4->setGeometry(10,40,100,30);
  QLabel_4->setMinimumSize(0,0);
  QLabel_4->setText(i18n("wget options"));

  lineWgetOption= new KLineEdit(QButtonGroup_2,"NoName");
  lineWgetOption->setGeometry(110,40,310,25);
  lineWgetOption->setMinimumSize(0,0);

  QLabel_5= new QLabel(QButtonGroup_2,"NoName");
  QLabel_5->setGeometry(10,70,360,30);
  QLabel_5->setMinimumSize(0,0);
  QLabel_5->setText(i18n("Edit your wget recource file ( ~/.wgetrc)"));

  buttonEditRcFile= new QPushButton(QButtonGroup_2,"NoName");
  buttonEditRcFile->setGeometry(370,70,50,25);
  buttonEditRcFile->setMinimumSize(0,0);
  buttonEditRcFile->setText(i18n("..."));

}
