/**********************************************************************
            --- KDevelop (KDlgEdit)  generated file ---

            Last generated: Fri Apr 7 23:17:41 2000

            DO NOT EDIT!!!  This file will be automatically
            regenerated by KDevelop.  All changes will be lost.

**********************************************************************/
#include <klocale.h>
#include <kurl.h>
#include <knumvalidator.h>

#include <qlayout.h>
#include <qspinbox.h>

#include "pictureview.h"
#include "tagimgdlg.h"

void  TagImgDlg::initDialog(){
  QGridLayout *grid = new QGridLayout( this );
  grid->setSpacing( 13 );
  grid->setMargin( 11 );
  labelImgSource= new QLabel(this,"labelImgSource");
  labelImgSource->setText(i18n("Image source:"));
  grid->addMultiCellWidget(labelImgSource, 0, 0, 0, 0);

  lineImgSource= new KLineEdit(this);
  grid->addMultiCellWidget(lineImgSource, 0, 0, 1, 3);

  buttonImgSource= new QPushButton(this,"NoName");
  buttonImgSource->setText(i18n("..."));
  grid->addMultiCellWidget(buttonImgSource, 0, 0, 4, 4);

  QLabel_4= new QLabel(this,"NoName");
  QLabel_4->setText(i18n("Width:"));
  grid->addMultiCellWidget(QLabel_4, 1, 1, 0, 0);

  lineWidth= new KLineEdit(this);
  lineWidth->setValidator( new KFloatValidator( lineWidth ) );
  grid->addMultiCellWidget(lineWidth, 1, 1, 1, 1);

  QLabel_5= new QLabel(this,"NoName");
  QLabel_5->setText(i18n("Height:"));
  grid->addMultiCellWidget(QLabel_5, 1, 1, 2, 2);

  lineHeight= new KLineEdit(this);
  lineHeight->setValidator( new KFloatValidator( lineHeight ) );
  grid->addMultiCellWidget(lineHeight, 1, 1, 3, 3);

  buttonRecalcImgSize= new QPushButton(this,"NoName");
  buttonRecalcImgSize->setText(i18n("..."));
  grid->addMultiCellWidget(buttonRecalcImgSize, 1, 1, 4, 4);

  QLabel_6= new QLabel(this);
  QLabel_6->setText(i18n("HSpace:"));
  grid->addMultiCellWidget(QLabel_6, 2, 2, 0, 0);

  lineHSpace= new KLineEdit(this);
  grid->addMultiCellWidget(lineHSpace, 2, 2, 1, 1);

  QLabel_7= new QLabel(this,"NoName");
  QLabel_7->setText(i18n("VSpace:"));
  grid->addMultiCellWidget(QLabel_7, 2, 2, 2, 2);

  lineVSpace= new KLineEdit(this);
  grid->addMultiCellWidget(lineVSpace, 2, 2, 3, 3);

  QLabel_8= new QLabel(this,"NoName");
  QLabel_8->setText(i18n("Alternate text:"));
  grid->addMultiCellWidget(QLabel_8, 3, 3, 0, 0);

  lineAltText= new KLineEdit(this);
  grid->addMultiCellWidget(lineAltText, 3, 3, 1, 4);

  QLabel_9= new QLabel(this,"NoName");
  QLabel_9->setText(i18n("Border:"));
  grid->addMultiCellWidget(QLabel_9, 4, 4, 0, 0);

  spinBorder= new QSpinBox(this,"NoName");
  spinBorder->setRange(0,20);
  grid->addMultiCellWidget(spinBorder, 4, 4, 1, 1);

  QLabel_10= new QLabel(this,"NoName");
  QLabel_10->setText(i18n("Align:"));
  grid->addMultiCellWidget(QLabel_10, 4, 4, 2, 2);

  comboAlign= new QComboBox(this,"NoName");
  grid->addMultiCellWidget(comboAlign, 4, 4, 3, 4);

  widgetImg= new PictureView(this);
  grid->addMultiCellWidget(widgetImg, 5, 10, 0, 4);

}
